# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField()),
                ('status', models.PositiveIntegerField(choices=[(0, 'PENDING'), (1, 'IN_PROGRESS'), (2, 'SUCCESS'), (3, 'FAIL')], default=0)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
    ]
