# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubedl_queue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadrequest',
            name='downloaded_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
